# Generated by Django 4.0.2 on 2022-02-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.DecimalField(decimal_places=4, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='successcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador', models.CharField(max_length=200)),
            ],
        ),
    ]
